INSERT INTO CLIENTE (CODCLI, CPF, NOME, SOBRENOME, EMAIL, DATA_NASCIMENTO, PONTOS, SEXO, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, DATA_INDICACAO, CLIENTE_INDICA)
VALUES (1, '12345678901', 'John', 'Doe', 'johndoe@example.com', TO_DATE('1990-05-05', 'YYYY-MM-DD'), 0, 'Male', '123 Main Street', '10A', 'Downtown', 'Cityville', '12345', TO_DATE('2023-05-08', 'YYYY-MM-DD'), 2);

INSERT INTO CLIENTE (CODCLI, CPF, NOME, SOBRENOME, EMAIL, DATA_NASCIMENTO, PONTOS, SEXO, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, DATA_INDICACAO, CLIENTE_INDICA)
VALUES (2, '98765432109', 'Jane', 'Smith', 'janesmith@example.com', TO_DATE('1992-08-20', 'YYYY-MM-DD'), 0, 'Female', '456 Elm Street', '20B', 'Suburbia', 'Townsville', '54321', TO_DATE('2023-05-28', 'YYYY-MM-DD'), 1);

INSERT INTO CLIENTE (CODCLI, CPF, NOME, SOBRENOME, EMAIL, DATA_NASCIMENTO, PONTOS, SEXO, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, DATA_INDICACAO, CLIENTE_INDICA)
VALUES (3, '11111111111', 'Michael', 'Johnson', 'michaeljohnson@example.com', TO_DATE('1985-09-12', 'YYYY-MM-DD'), 0, 'Male', '789 Oak Avenue', '15C', 'Suburbia', 'Townsville', '54321', TO_DATE('2023-05-28', 'YYYY-MM-DD'), 1);

INSERT INTO CLIENTE (CODCLI, CPF, NOME, SOBRENOME, EMAIL, DATA_NASCIMENTO, PONTOS, SEXO, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, DATA_INDICACAO, CLIENTE_INDICA)
VALUES (4, '22222222222', 'Emily', 'Brown', 'emilybrown@example.com', TO_DATE('1993-06-18', 'YYYY-MM-DD'), 0, 'Female', '567 Pine Street', '7B', 'Downtown', 'Cityville', '12345', TO_DATE('2023-05-28', 'YYYY-MM-DD'), 2);

INSERT INTO CLIENTE (CODCLI, CPF, NOME, SOBRENOME, EMAIL, DATA_NASCIMENTO, PONTOS, SEXO, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, DATA_INDICACAO, CLIENTE_INDICA)
VALUES (5, '33333333333', 'David', 'Wilson', 'davidwilson@example.com', TO_DATE('1988-12-30', 'YYYY-MM-DD'), 0, 'Male', '321 Maple Avenue', '3A', 'Suburbia', 'Townsville', '54321', TO_DATE('2023-05-28', 'YYYY-MM-DD'), 3);

INSERT INTO CLIENTE (CODCLI, CPF, NOME, SOBRENOME, EMAIL, DATA_NASCIMENTO, PONTOS, SEXO, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, DATA_INDICACAO, CLIENTE_INDICA)
VALUES (6, '44444444444', 'Sarah', 'Taylor', 'sarahtaylor@example.com', TO_DATE('1995-03-25', 'YYYY-MM-DD'), 0, 'Female', '789 Oak Avenue', '15C', 'Downtown', 'Cityville', '12345', TO_DATE('2023-05-28', 'YYYY-MM-DD'), 4);

INSERT INTO CLIENTE (CODCLI, CPF, NOME, SOBRENOME, EMAIL, DATA_NASCIMENTO, PONTOS, SEXO, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, DATA_INDICACAO, CLIENTE_INDICA)
VALUES (7, '55555555555', 'Daniel', 'Miller', 'danielmiller@example.com', TO_DATE('1991-11-09', 'YYYY-MM-DD'), 0, 'Male', '234 Elm Street', '8B', 'Suburbia', 'Townsville', '54321', TO_DATE('2023-05-28', 'YYYY-MM-DD'), 5);

INSERT INTO CLIENTE (CODCLI, CPF, NOME, SOBRENOME, EMAIL, DATA_NASCIMENTO, PONTOS, SEXO, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, DATA_INDICACAO, CLIENTE_INDICA)
VALUES (8, '66666666666', 'Olivia', 'Anderson', 'oliviaanderson@example.com', TO_DATE('1994-07-17', 'YYYY-MM-DD'), 0, 'Female', '987 Oak Avenue', '25C', 'Downtown', 'Cityville', '12345', TO_DATE('2023-05-28', 'YYYY-MM-DD'), 6);

INSERT INTO CLIENTE (CODCLI, CPF, NOME, SOBRENOME, EMAIL, DATA_NASCIMENTO, PONTOS, SEXO, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, DATA_INDICACAO, CLIENTE_INDICA)
VALUES (9, '77777777777', 'Andrew', 'Wilson', 'andrewwilson@example.com', TO_DATE('1987-02-14', 'YYYY-MM-DD'), 0, 'Male', '567 Pine Street', '7B', 'Suburbia', 'Townsville', '54321', TO_DATE('2023-05-28', 'YYYY-MM-DD'), 7);

INSERT INTO CLIENTE (CODCLI, CPF, NOME, SOBRENOME, EMAIL, DATA_NASCIMENTO, PONTOS, SEXO, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, DATA_INDICACAO, CLIENTE_INDICA)
VALUES (10, '88888888888', 'Sophia', 'Walker', 'sophiawalker@example.com', TO_DATE('1996-09-05', 'YYYY-MM-DD'), 0, 'Female', '890 Oak Avenue', '12C', 'Downtown', 'Cityville', '12345', TO_DATE('2023-05-28', 'YYYY-MM-DD'), 8);


INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (1, '9222154516');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (2, '4626178260');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (3, '8521764767');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (4, '8223605635');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (5, '9721377068');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (6, '6935318027');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (7, '8223849959');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (8, '9721989561');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (9, '1838629824');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (10, '9924834549');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (3, '7431220952');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (2, '9438505223');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (6, '6933634523');

INSERT INTO TRANSPORTADORA(CODTRANS, NOME, EMAIL, TELEFONE, SITE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (1, 'Full Entregas', 'fullentregas@email.com', '8333334113', 'fullentregas.com', 'Rua Full Entregas', '1000', 'Malvinas', 'Campina Grande', '58417075' );
INSERT INTO TRANSPORTADORA(CODTRANS, NOME, EMAIL, TELEFONE, SITE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (2, 'Transportando com Amor', 'transporte.amor@email.com', '8426560895', 'transportandoamor.com', 'Rua Transportando com Amor', '2000', 'Parque Taubateguassu', 'Taubaté', '12071330');
INSERT INTO TRANSPORTADORA(CODTRANS, NOME, EMAIL, TELEFONE, SITE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (3, 'Transporte Top', 'transportetop@email.com', '9234682154', 'transportetop.com', 'Rua Transporte Top', '3000', 'Cidade Gerardo Cristino', 'Sobral', '62051270');
INSERT INTO TRANSPORTADORA(CODTRANS, NOME, EMAIL, TELEFONE, SITE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (4, 'Fast Entregas', 'fastentregas@email.com', '8756868124', 'fastentregas.com', 'Rua Fast Entregas', '4000', 'Paciência', 'Rio de Janeiro', '23585670');
INSERT INTO TRANSPORTADORA(CODTRANS, NOME, EMAIL, TELEFONE, SITE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (5, 'Pediu Chegou', 'pediuchegou@email.com', '2133524545', 'pediuchegou.com', 'Rua Pediu Chegou', '5000', 'São Cristóvão', 'Criciúma', '88802502');

INSERT INTO FORNECEDOR (CODFORN, CNPJ, NOME, HOME_PAGE, EMAIL, TELEFONE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES ();
INSERT INTO FORNECEDOR (CODFORN, CNPJ, NOME, HOME_PAGE, EMAIL, TELEFONE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES ();
INSERT INTO FORNECEDOR (CODFORN, CNPJ, NOME, HOME_PAGE, EMAIL, TELEFONE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES ();
INSERT INTO FORNECEDOR (CODFORN, CNPJ, NOME, HOME_PAGE, EMAIL, TELEFONE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES ();

INSERT INTO CATEGORIA(CODCAT, NOME)
VALUES();
INSERT INTO CATEGORIA(CODCAT, NOME)
VALUES();
INSERT INTO CATEGORIA(CODCAT, NOME)
VALUES();
INSERT INTO CATEGORIA(CODCAT, NOME)
VALUES();
INSERT INTO CATEGORIA(CODCAT, NOME)
VALUES();
INSERT INTO CATEGORIA(CODCAT, NOME)
VALUES();
INSERT INTO CATEGORIA(CODCAT, NOME)
VALUES();


INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();


INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES ();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();

INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES ();
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES ();
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES ();
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES ();
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES ();

INSERT INTO NOTA_FISCAL(CODNF, NUMERO, SERIE, INSCRICAO_ESTADUAL, CHAVE_ACESSO, DATA_NF, VALOR_TOTAL, COD_ORDEM_COMPRA)
VALUES ();
INSERT INTO NOTA_FISCAL(CODNF, NUMERO, SERIE, INSCRICAO_ESTADUAL, CHAVE_ACESSO, DATA_NF, VALOR_TOTAL, COD_ORDEM_COMPRA)
VALUES ();

INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (1, 1, 10,);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (3, 12, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (4, 4, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (5, 10, 10)
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (6, 6, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (7, 3, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (8, 14, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (9, 2, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (10, 7, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (11, 9, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (12, 13, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (13, 1, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (14, 11, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (15, 5, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (16, 15, 10);


INSERT INTO COMPRA_AVALIA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, NOTA, DESCRICAO)
VALUES (1, 1, 4, "Produto chegou defeituoso");
INSERT INTO COMPRA_AVALIA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, NOTA, DESCRICAO)
VALUES (3, 1, 5, 'Ótima qualidade e atendimento');
INSERT INTO COMPRA_AVALIA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, NOTA, DESCRICAO)
VALUES (4, 3, 2, 'Embalagem danificada, produto OK');
INSERT INTO COMPRA_AVALIA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, NOTA, DESCRICAO)
VALUES (6, 3, 5, 'Produto conforme o esperado');
INSERT INTO COMPRA_AVALIA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, NOTA, DESCRICAO)
VALUES (7, 1, 2, 'Atendimento ao cliente precisa melhorar');