INSERT INTO CLIENTE (codcli, cpf, nome, sobrenome, email, data_nascimento, pontos, sexo, end_rua, end_num, end_bairro, end_cidade, end_cep, data_indicacao, cliente_indica)
VALUES ();
INSERT INTO CLIENTE (codcli, cpf, nome, sobrenome, email, data_nascimento, pontos, sexo, end_rua, end_num, end_bairro, end_cidade, end_cep, data_indicacao, cliente_indica)
VALUES ();
INSERT INTO CLIENTE (codcli, cpf, nome, sobrenome, email, data_nascimento, pontos, sexo, end_rua, end_num, end_bairro, end_cidade, end_cep, data_indicacao, cliente_indica)
VALUES ();
INSERT INTO CLIENTE (codcli, cpf, nome, sobrenome, email, data_nascimento, pontos, sexo, end_rua, end_num, end_bairro, end_cidade, end_cep, data_indicacao, cliente_indica)
VALUES ();
INSERT INTO CLIENTE (codcli, cpf, nome, sobrenome, email, data_nascimento, pontos, sexo, end_rua, end_num, end_bairro, end_cidade, end_cep, data_indicacao, cliente_indica)
VALUES ();
INSERT INTO CLIENTE (codcli, cpf, nome, sobrenome, email, data_nascimento, pontos, sexo, end_rua, end_num, end_bairro, end_cidade, end_cep, data_indicacao, cliente_indica)
VALUES ();
INSERT INTO CLIENTE (codcli, cpf, nome, sobrenome, email, data_nascimento, pontos, sexo, end_rua, end_num, end_bairro, end_cidade, end_cep, data_indicacao, cliente_indica)
VALUES ();

INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (1, '9222154516');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (2, '4626178260');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (3, '8521764767');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (4, '8223605635');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (5, '9721377068');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (6, '6935318027');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (7, '8223849959');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (8, '9721989561');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (9, '1838629824');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (10, '9924834549');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (3, '7431220952');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (2, '9438505223');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (6, '6933634523');

INSERT INTO TRANSPORTADORA(CODTRANS, NOME, EMAIL, TELEFONE, SITE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (1, 'Full Entregas', 'fullentregas@email.com', '8333334113', 'fullentregas.com', 'Rua Full Entregas', '1000', 'Malvinas', 'Campina Grande', '58417075' );
INSERT INTO TRANSPORTADORA(CODTRANS, NOME, EMAIL, TELEFONE, SITE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (2, 'Transportando com Amor', 'transporte.amor@email.com', '8426560895', 'transportandoamor.com', 'Rua Transportando com Amor', '2000', 'Parque Taubateguassu', 'Taubaté', '12071330');
INSERT INTO TRANSPORTADORA(CODTRANS, NOME, EMAIL, TELEFONE, SITE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (3, 'Transporte Top', 'transportetop@email.com', '9234682154', 'transportetop.com', 'Rua Transporte Top', '3000', 'Cidade Gerardo Cristino', 'Sobral', '62051270');
INSERT INTO TRANSPORTADORA(CODTRANS, NOME, EMAIL, TELEFONE, SITE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (4, 'Fast Entregas', 'fastentregas@email.com', '8756868124', 'fastentregas.com', 'Rua Fast Entregas', '4000', 'Paciência', 'Rio de Janeiro', '23585670');
INSERT INTO TRANSPORTADORA(CODTRANS, NOME, EMAIL, TELEFONE, SITE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (5, 'Pediu Chegou', 'pediuchegou@email.com', '2133524545', 'pediuchegou.com', 'Rua Pediu Chegou', '5000', 'São Cristóvão', 'Criciúma', '88802502');

INSERT INTO FORNECEDOR (CODFORN, CNPJ, NOME, HOME_PAGE, EMAIL, TELEFONE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES ();
INSERT INTO FORNECEDOR (CODFORN, CNPJ, NOME, HOME_PAGE, EMAIL, TELEFONE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES ();
INSERT INTO FORNECEDOR (CODFORN, CNPJ, NOME, HOME_PAGE, EMAIL, TELEFONE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES ();
INSERT INTO FORNECEDOR (CODFORN, CNPJ, NOME, HOME_PAGE, EMAIL, TELEFONE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES ();

INSERT INTO CATEGORIA(CODCAT, NOME)
VALUES();
INSERT INTO CATEGORIA(CODCAT, NOME)
VALUES();
INSERT INTO CATEGORIA(CODCAT, NOME)
VALUES();
INSERT INTO CATEGORIA(CODCAT, NOME)
VALUES();
INSERT INTO CATEGORIA(CODCAT, NOME)
VALUES();
INSERT INTO CATEGORIA(CODCAT, NOME)
VALUES();
INSERT INTO CATEGORIA(CODCAT, NOME)
VALUES();


INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();


INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES ();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();

INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES ();
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES ();
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES ();
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES ();
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES ();

INSERT INTO NOTA_FISCAL(CODNF, NUMERO, SERIE, INSCRICAO_ESTADUAL, CHAVE_ACESSO, DATA_NF, VALOR_TOTAL, COD_ORDEM_COMPRA)
VALUES ();
INSERT INTO NOTA_FISCAL(CODNF, NUMERO, SERIE, INSCRICAO_ESTADUAL, CHAVE_ACESSO, DATA_NF, VALOR_TOTAL, COD_ORDEM_COMPRA)
VALUES ();

INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (1, 1, 10,);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (3, 12, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (4, 4, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (5, 10, 10)
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (6, 6, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (7, 3, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (8, 14, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (9, 2, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (10, 7, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (11, 9, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (12, 13, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (13, 1, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (14, 11, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (15, 5, 10);
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES (16, 15, 10);


INSERT INTO COMPRA_AVALIA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, NOTA, DESCRICAO)
VALUES (1, 1, 4, "Produto chegou defeituoso");
INSERT INTO COMPRA_AVALIA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, NOTA, DESCRICAO)
VALUES (3, 1, 5, 'Ótima qualidade e atendimento');
INSERT INTO COMPRA_AVALIA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, NOTA, DESCRICAO)
VALUES (4, 3, 2, 'Embalagem danificada, produto OK');
INSERT INTO COMPRA_AVALIA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, NOTA, DESCRICAO)
VALUES (6, 3, 5, 'Produto conforme o esperado');
INSERT INTO COMPRA_AVALIA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, NOTA, DESCRICAO)
VALUES (7, 1, 2, 'Atendimento ao cliente precisa melhorar');