INSERT INTO CLIENTE (codcli, cpf, nome, sobrenome, email, data_nascimento, pontos, sexo, end_rua, end_num, end_bairro, end_cidade, end_cep, data_indicacao, cliente_indica)
VALUES ();
INSERT INTO CLIENTE (codcli, cpf, nome, sobrenome, email, data_nascimento, pontos, sexo, end_rua, end_num, end_bairro, end_cidade, end_cep, data_indicacao, cliente_indica)
VALUES ();
INSERT INTO CLIENTE (codcli, cpf, nome, sobrenome, email, data_nascimento, pontos, sexo, end_rua, end_num, end_bairro, end_cidade, end_cep, data_indicacao, cliente_indica)
VALUES ();
INSERT INTO CLIENTE (codcli, cpf, nome, sobrenome, email, data_nascimento, pontos, sexo, end_rua, end_num, end_bairro, end_cidade, end_cep, data_indicacao, cliente_indica)
VALUES ();
INSERT INTO CLIENTE (codcli, cpf, nome, sobrenome, email, data_nascimento, pontos, sexo, end_rua, end_num, end_bairro, end_cidade, end_cep, data_indicacao, cliente_indica)
VALUES ();
INSERT INTO CLIENTE (codcli, cpf, nome, sobrenome, email, data_nascimento, pontos, sexo, end_rua, end_num, end_bairro, end_cidade, end_cep, data_indicacao, cliente_indica)
VALUES ();
INSERT INTO CLIENTE (codcli, cpf, nome, sobrenome, email, data_nascimento, pontos, sexo, end_rua, end_num, end_bairro, end_cidade, end_cep, data_indicacao, cliente_indica)
VALUES ();

INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (1, '9222154516');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (2, '4626178260');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (3, '8521764767');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (4, '8223605635');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (5, '9721377068');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (6, '6935318027');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (7, '8223849959');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (8, '9721989561');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (9, '1838629824');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (10, '9924834549');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (3, '7431220952');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (2, '9438505223');
INSERT INTO TELEFONES_CLIENTE (cod_cli, numero)
VALUES (6, '6933634523');

INSERT INTO TRANSPORTADORA(CODTRANS, NOME, EMAIL, TELEFONE, SITE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (1, 'Full Entregas', 'fullentregas@email.com', '8333334113', 'fullentregas.com', 'Rua Full Entregas', '1000', 'Malvinas', 'Campina Grande', '58417075' );
INSERT INTO TRANSPORTADORA(CODTRANS, NOME, EMAIL, TELEFONE, SITE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (2, 'Transportando com Amor', 'transporte.amor@email.com', '8426560895', 'transportandoamor.com', 'Rua Transportando com Amor', '2000', 'Parque Taubateguassu', 'Taubaté', '12071330');
INSERT INTO TRANSPORTADORA(CODTRANS, NOME, EMAIL, TELEFONE, SITE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (3, 'Transporte Top', 'transportetop@email.com', '9234682154', 'transportetop.com', 'Rua Transporte Top', '3000', 'Cidade Gerardo Cristino', 'Sobral', '62051270');
INSERT INTO TRANSPORTADORA(CODTRANS, NOME, EMAIL, TELEFONE, SITE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (4, 'Fast Entregas', 'fastentregas@email.com', '8756868124', 'fastentregas.com', 'Rua Fast Entregas', '4000', 'Paciência', 'Rio de Janeiro', '23585670');
INSERT INTO TRANSPORTADORA(CODTRANS, NOME, EMAIL, TELEFONE, SITE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (5, 'Pediu Chegou', 'pediuchegou@email.com', '2133524545', 'pediuchegou.com', 'Rua Pediu Chegou', '5000', 'São Cristóvão', 'Criciúma', '88802502');

-- Inserção de Fornecedores na tabela --

INSERT INTO FORNECEDOR (CODFORN, CNPJ, NOME, HOME_PAGE, EMAIL, TELEFONE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (FORNECEDOR_SEQ.NEXTVAL, '047697320001-00', 'ISIS LTDA.', 'www.saborisis.com.br', 'contato@saborisis.com.br', '(83)35222222', 'R. Manoel Celestino de Paula', '101', 'Alto do Cruzeiro', 'Sousa', '58806658');

INSERT INTO FORNECEDOR (CODFORN, CNPJ, NOME, HOME_PAGE, EMAIL, TELEFONE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (FORNECEDOR_SEQ.NEXTVAL, '556904580001-01', 'BOMBRIL', 'BOMBRIL.COM', 'CONTATO@BOMBRIL.COM', '(45)21540278', 'Rua Santa Quitéria', '1001', 'Santa Mônica', 'Camaragibe', '54767260');

INSERT INTO FORNECEDOR (CODFORN, CNPJ, NOME, HOME_PAGE, EMAIL, TELEFONE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (FORNECEDOR_SEQ.NEXTVAL, '564174760001-87', 'ALIMENTOS Gems', 'ALIMENTOSGems.COM', 'CONTATO@ALIMENTOS Gems.COM', '(96)22254327', 'Rua Vinte e Sete', '27', 'Recanto do Turu', 'São Luís', '65068888');

INSERT INTO FORNECEDOR (CODFORN, CNPJ, NOME, HOME_PAGE, EMAIL, TELEFONE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (FORNECEDOR_SEQ.NEXTVAL, '103911940001-57', 'Trilogy Laticínios', 'TrilogyLaticínios.COM', 'CONTATO@TrilogyLaticínios.COM', '(83)23153426', 'Rua Antônio Marinho', '88', 'Bodocongó', 'Campina Grande', '58430250');

INSERT INTO FORNECEDOR (CODFORN, CNPJ, NOME, HOME_PAGE, EMAIL, TELEFONE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (FORNECEDOR_SEQ.NEXTVAL, '445247010001-03', 'Leandro e Mateus Padaria Ltda', 'WWW.leandroemateuspadarialtda.com.br', 'fiscal@leandroemateuspadarialtda.com.br', '(83)25109571', 'Rua Lopes Trovão', '269', 'Mandacaru', 'João Pessoa', '58027080');

INSERT INTO FORNECEDOR (CODFORN, CNPJ, NOME, HOME_PAGE, EMAIL, TELEFONE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (FORNECEDOR_SEQ.NEXTVAL, '175296200001-15', 'Lúcia e Heloise Pizzaria Ltda', 'www.luciaeheloisepizzarialtda.com.br', 'faleconosco@luciaeheloisepizzarialtda.com.br', '(83)27027635', 'Rua das Peperônias', '343', 'Mangabeira', 'João Pessoa', '58059714');

INSERT INTO FORNECEDOR (CODFORN, CNPJ, NOME, HOME_PAGE, EMAIL, TELEFONE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (FORNECEDOR_SEQ.NEXTVAL, '891103820001-10', 'Sophia e Rodrigo Gráfica Ltda', 'www.sophiaerodrigograficaltda.com.br', 'cobranca@sophiaerodrigograficaltda.com.br', '(83)37766713', 'Rua Amazonas', '885', 'Popular', 'Santa Rita', '58301545');

INSERT INTO FORNECEDOR (CODFORN, CNPJ, NOME, HOME_PAGE, EMAIL, TELEFONE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (FORNECEDOR_SEQ.NEXTVAL, '783621320001-50', 'Felipe e Jorge Doces & Salgados Ltda', 'www.felipeejorgedocessalgadosltda.com.br', 'contato@felipeejorgedocessalgadosltda.com.br', '(83)37931507', 'Rua Frei Pascoal', '221', 'Malvinas', 'Campina Grande', '58432740');

INSERT INTO FORNECEDOR (CODFORN, CNPJ, NOME, HOME_PAGE, EMAIL, TELEFONE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (FORNECEDOR_SEQ.NEXTVAL, '496910540001-30', 'Valentina e Emily Marcenaria ME', 'www.valentinaeemilymarcenariame.com.br', 'marketing@valentinaeemilymarcenariame.com.br', '(83)37535083', 'Rua Frei Damião de Bozzano', '465', 'Renascer', 'Cabedelo', '58108284');

INSERT INTO FORNECEDOR (CODFORN, CNPJ, NOME, HOME_PAGE, EMAIL, TELEFONE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP)
VALUES (FORNECEDOR_SEQ.NEXTVAL, '695002690001-33', 'Sabrina e Emilly Comercio de Bebidas ME', 'www.sabrinaeemillycomerciodebebidasme.com.br', 'cobranca@sabrinaeemillycomerciodebebidasme.com.br', '(83)28658387', 'Rua Maria Batista Palitot', '397', 'Ipês', 'João Pessoa', '58028430');

------------------------------------------------------------------

-- Inserção de Categorias na tabela --

INSERT INTO CATEGORIA (CODCAT, NOME) VALUES (CATEGORIA_SEQ.NEXTVAL, 'jogos');

INSERT INTO CATEGORIA (CODCAT, NOME) VALUES (CATEGORIA_SEQ.NEXTVAL, 'informatica');

INSERT INTO CATEGORIA (CODCAT, NOME) VALUES (CATEGORIA_SEQ.NEXTVAL, 'alimentos vegetais');

INSERT INTO CATEGORIA (CODCAT, NOME) VALUES (CATEGORIA_SEQ.NEXTVAL, 'alimentos animais');

INSERT INTO CATEGORIA (CODCAT, NOME) VALUES (CATEGORIA_SEQ.NEXTVAL, 'maquiagem');

INSERT INTO CATEGORIA (CODCAT, NOME) VALUES (CATEGORIA_SEQ.NEXTVAL, 'cama, mesa e banho');

INSERT INTO CATEGORIA (CODCAT, NOME) VALUES (CATEGORIA_SEQ.NEXTVAL, 'eletrodomesticos');

INSERT INTO CATEGORIA (CODCAT, NOME) VALUES (CATEGORIA_SEQ.NEXTVAL, 'limpesa');

INSERT INTO CATEGORIA (CODCAT, NOME) VALUES (CATEGORIA_SEQ.NEXTVAL, 'brinquedos');

INSERT INTO CATEGORIA (CODCAT, NOME) VALUES (CATEGORIA_SEQ.NEXTVAL, 'moveis');

------------------------------------------------------------------

INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();
INSERT INTO PRODUTO(CODPROD, NOME, PRECO_COMPRA, PRECO_VENDA, DATA_FABRICACAO, DESCRICAO, ESPECIFICACAO, DATA_VALIDADE, COD_CATEGORIA, QUANTIDADE)
VALUES ();


INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES ();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES();

INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES ();
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES ();
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES ();
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES ();
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES ();

INSERT INTO NOTA_FISCAL(CODNF, NUMERO, SERIE, INSCRICAO_ESTADUAL, CHAVE_ACESSO, DATA_NF, VALOR_TOTAL, COD_ORDEM_COMPRA)
VALUES ();
INSERT INTO NOTA_FISCAL(CODNF, NUMERO, SERIE, INSCRICAO_ESTADUAL, CHAVE_ACESSO, DATA_NF, VALOR_TOTAL, COD_ORDEM_COMPRA)
VALUES ();

INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES ();
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES ();
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES ();
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES ();
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES ();
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES ();
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES ();
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES ();
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES ();
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES ();
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES ();
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES ();
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES ();
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES ();
INSERT INTO COMPRA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, QUANTIDADE, VALOR_ATUAL)
VALUES ();


INSERT INTO COMPRA_AVALIA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, NOTA, DESCRICAO)
VALUES ();
INSERT INTO COMPRA_AVALIA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, NOTA, DESCRICAO)
VALUES ();
INSERT INTO COMPRA_AVALIA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, NOTA, DESCRICAO)
VALUES ();
INSERT INTO COMPRA_AVALIA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, NOTA, DESCRICAO)
VALUES ();
INSERT INTO COMPRA_AVALIA_PRODUTO(CODIGO_COMPRA, CODIGO_PRODUTO, NOTA, DESCRICAO)
VALUES ();
