INSERT INTO FORNECIMENTO(CODIGO_PRODUTO,CODIGO_FORNECEDOR) VALUES (1,5);
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO,CODIGO_FORNECEDOR) VALUES (2,7);
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO,CODIGO_FORNECEDOR) VALUES (3,7);
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO,CODIGO_FORNECEDOR) VALUES (4,2);
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO,CODIGO_FORNECEDOR) VALUES (5,3);
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO,CODIGO_FORNECEDOR) VALUES (6,3);
INSERT INTO FORNECIMENTO(CODIGO_PRODUTO,CODIGO_FORNECEDOR) VALUES (7,3);
