-- Ordens de Compra Cadastradas

-- ORDEM DE COMPRA
CREATE TABLE ORDEM_DE_COMPRA (
  CODORDEM                 INTEGER,
  DATA_COMPRA             DATE DEFAULT SYSDATE NOT NULL,
  STATUS                  VARCHAR(20) DEFAULT 'AGUARDANDO PAGAMENTO' NOT NULL,
  DESCONTO                NUMBER(6,2),
  VALOR_FRETE             NUMBER(10,2) NOT NULL, 
  END_RUA         VARCHAR(50),
  END_NUM         CHAR(5),
  END_BAIRRO      CHAR(20),
  END_CIDADE      CHAR(30),
  END_CEP         CHAR(8),
  CODIGO_CLIENTE          INTEGER NOT NULL,
  CODIGO_TRANSPORTADORA   INTEGER NOT NULL,
  CONSTRAINT ORDEM_DE_COMPRA_PK               PRIMARY KEY (CODORDEM),
  CONSTRAINT CODIGO_CLIENTE_COMPRA_FK         FOREIGN KEY (CODIGO_CLIENTE)        REFERENCES CLIENTE(CODCLI),
  CONSTRAINT CODIGO_TRANSPORTADORA_COMPRA_FK  FOREIGN KEY (CODIGO_TRANSPORTADORA) REFERENCES TRANSPORTADORA(CODTRANS),
  CONSTRAINT CHECK_STATUS  CHECK (STATUS IN ('AGUARDANDO PAGAMENTO', 'EM SEPARACAO', 'EM TRANSPORTE', 'FINALIZADA')) 
);

INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES (ORDEMDECOMPRA_SEQ.NEXTVAL,TO_DATE('2023-05-29','YYYY-MM-DD'),'EM SEPARACAO',0,10,'Travessa Oitava da Setentrional','72B','Araxá','Macapá','68903777',2,1);
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES (ORDEMDECOMPRA_SEQ.NEXTVAL,TO_DATE('2023-04-27','YYYY-MM-DD'),'EM TRANSPORTE',10,20,'Rua Brasilândia',14,'Tiradentes','Campo Grande','79041050',3,1);
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES (ORDEMDECOMPRA_SEQ.NEXTVAL,TO_DATE('2023-03-27','YYYY-MM-DD'),'FINALIZADA',0,30,'Quadra QNM 7','18C','Ceilândia Sul','Brasília','72215070',4,3);
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES (ORDEMDECOMPRA_SEQ.NEXTVAL,TO_DATE('2023-03-27','YYYY-MM-DD'),'FINALIZADA',0,0,'Quadra EQNN 22/24 Bloco F','07F','Ceilândia Sul','Brasília','72220576',5,3);
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES (ORDEMDECOMPRA_SEQ.NEXTVAL,TO_DATE('2023-06-06','YYYY-MM-DD'),'AGUARDANDO PAGAMENTO',5,12,'Rua ED 7','195','Setor Estrela Dalva','Goiânia','74475744',6,1);
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES (ORDEMDECOMPRA_SEQ.NEXTVAL,TO_DATE('2020-01-06','YYYY-MM-DD'),'FINALIZADA',15,15,'Rua Projetada 84','S/N','Conduru','Picos','64608370',7,2);
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES (ORDEMDECOMPRA_SEQ.NEXTVAL,TO_DATE('2020-01-06','YYYY-MM-DD'),'FINALIZADA',0,25,'Rua Joaquim Gomes Ferreira','203','Vargem Grande','Rio de Janeiro','22785660',8,4);
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES (ORDEMDECOMPRA_SEQ.NEXTVAL,TO_DATE('2023-04-06','YYYY-MM-DD'),'EM TRANSPORTE',11,20,'Rua Vereadora Maria Carolina da Costa Carmo','119','Jardim América','Itaguaí','23812750',9,1);
INSERT INTO ORDEM_DE_COMPRA (CODORDEM, DATA_COMPRA, STATUS, DESCONTO, VALOR_FRETE, END_RUA, END_NUM, END_BAIRRO, END_CIDADE, END_CEP, CODIGO_CLIENTE, CODIGO_TRANSPORTADORA)
VALUES (ORDEMDECOMPRA_SEQ.NEXTVAL,TO_DATE('2023-02-06','YYYY-MM-DD'),'AGUARDANDO PAGAMENTO',10,30,'Travessa Zona Ampliada','124','Capoeira','Rio Branco','69905002',10,1);

-- Pelo menos uma ordem de compra no ano de 2020

-- A soma das comprar de pelo menos uma cidade deve ser maior que 240

-- Pelo menos duas compras feitas pela transportadora full entregas

-- Duas datas distintas de ordem de compra



